### ISSUE TITLE
silverstripe/versioned 1.5.1 => 1.6.0 update add _Live to tables that don't have a _Live table

### ISSUE THREAD

**Issue by TheBnl** [silverstripe/silverstripe-versioned#283] opened 2020-07-17 09:46 UTC
After updating versioned to 1.6.0 `_Live` gets added to tables that use the Versioned extension without Live or Draft.
In my case its the Silvershop Variation model that has the following extension:
```php
namespace SilverShop\Model\Variation;

class Variation extends DataObject implements Buyable
{
    private static $extensions = [
        Versioned::class . '.versioned'
    ];
}
```

This gives me the following error when executing a quiry trough the ORM:

```
[Emergency] Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query: 
SELECT DISTINCT "SiteTree_Live"."ID", "SiteTree_Live"."Title" AS "_SortColumn0" FROM "SiteTree_Live" 
LEFT JOIN "Page_Live" ON "Page_Live"."ID" = "SiteTree_Live"."ID" 
LEFT JOIN "SilverShop_Product_Live" ON "SilverShop_Product_Live"."ID" = "SiteTree_Live"."ID" 
LEFT JOIN `"SilverShop_Variation_Live"` AS "variations_SilverShop_Variation" ON "variations_SilverShop_Variation"."ProductID" = "SiteTree_Live"."ID" 
WHERE (("SilverShop_Product_Live"."BasePrice" > ?) OR ("variations_SilverShop_Variation"."Price" > ?)) AND ("SiteTree_Live"."ID" IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)) AND ("SilverShop_Product_Live"."SeasonID" IN (?, ?, ?, ?, ?, ?)) AND ("SiteTree_Live"."ClassName" IN (?, ?)) 
ORDER BY "_SortColumn0" ASC 

Table `'X.SilverShop_Variation_Live'` doesn't exist
```

## PR's

- [x] https://github.com/silverstripe/silverstripe-versioned/pull/285

**Comment by kinglozzer** [comment] 2020-07-17 10:07
Looks like a regression from https://github.com/silverstripe/silverstripe-versioned/pull/253

**Comment by kinglozzer** [comment] 2020-07-17 10:16
Possible fix is to use the `Versioned::hasStages()` method:

```php
public function updateJoinTableName($class, $table, &$updated)
{
    $inst = Injector::inst()->get($class);
    if (!$inst->hasExtension(Versioned::class) || !$inst->hasStages())
        return;
    }

    /** @var Versioned $versioned */
    $versioned = Injector::inst()->get(Versioned::class);
    $stage = $versioned->get_stage();
    $updated = $versioned->stageTable($table, $stage);
}
```

**Comment by TheBnl** [comment] 2020-07-19 13:07
Thanks for looking into this! 
I'm able to test the suggested fix coming tuesday.

**Comment by TheBnl** [comment] 2020-07-20 07:47
I can confirm that this fixes the issue

**Comment by TheBnl** [comment] 2020-07-20 07:53
I've created a PR for this issue, so i can implement the fix 😉

**Comment by maxime-rainville** [comment] 2020-07-20 23:17
Merged the related PR. I'll run a build of the kitchen sink. If everything is green, I'll do a patch release of versioned.

**Comment by maxime-rainville** [comment] 2020-07-21 01:56
Just released `silverstripe/versioned` 1.6.1 with this fix. https://github.com/silverstripe/silverstripe-versioned/releases/tag/1.6.1

**Closed** 2020-07-21 01:57 UTC
Labels: affects/v4, change/patch, feedback-required/core-team, impact/critical, type/bug

**Comment by dnsl48** [comment] 2020-07-21 02:18
@TheBnl thank you for reporting that and the contribution is much appreciated!

**Comment by TheBnl** [comment] 2020-07-21 09:13
Thanks for the quick actions!
