### ISSUE TITLE
Version number for many-many-through "join" items doesn’t ever change

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-versioned#130] opened 2018-03-05 17:05 UTC
Perhaps this is expected, just struck me as odd. Given the following versioned models:

- Project
- Type
- ProjectType - the “through“ object linking projects & types

I added a `CheckboxSetField` for linking them which works, but every record in the `ProjectType_Versions` table has the same `Version` number. For example, if I tick a “type” & publish, then untick & publish, then re-tick & publish the same “type”, there are 2 records in the versions table that are effectively identical:

<img width="882" alt="screen shot 2018-03-05 at 17 03 47" src="https://user-images.githubusercontent.com/1655548/36988616-330f558a-2097-11e8-8192-8677f51daf0d.png">

**Comment by tractorcow** [comment] 2018-04-15 23:07
I'll look into this and respond to it later.

**Comment by tractorcow** [comment] 2018-04-16 00:05
If you aren't making changes to the relationship, and you save, and there are new rows created, it probably shouldn't create a new version just for draft.

However, if you publish a record it probably should create a new row. Except in your example above I don't see `WasPublished` set to 1, so I'm not sure what is going on specifically in your example.

What would concern me is that the ID column of ProjectType is incremented for each save; If you need to create a new record each save, instead of re-using existing mapping records, that may be a problem.

**Comment by tractorcow** [comment] 2018-04-16 00:07
@kinglozzer please provide framework version, and either some example code and I'll reproduce it locally. Make sure you declare:
 - any ownership
 - specific relationship config
 - formfields used

**Comment by tractorcow** [comment] 2018-04-16 23:25
Thanks I'll check it out now. ;)

**Comment by tractorcow** [comment] 2018-04-16 23:48
Ok, I've done my research and I can resolve this with explanation for how this works;

Because the ProjectType has NO extra fields (only parent / child relations) there will never be the need to create a "new" version of an existing record.

When you unassign a many_many and re-assign it, you aren't creating a new version of the same relation, you are deleting that record, and creating a brand new record for that relation. Two record creations (different RecordID) but each is only ever created and never modified (unless it's deleted). These versions never get a chance to create Version 2, because their values never change.

If you look at your example, the records aren't identical, they have two different RecordIDs. This would be synonymous with me creating a home page, archiving it, and then manually re-creating a brand new home page with identical fields. It would have the same Version (assuming it was saved the same number of times) but it would have a different ID (RecordID in versions table).

I hope that explains things!

**Closed by tractorcow** 2018-04-16 23:48 UTC
Labels: affects/v4, feedback-required/core-team, impact/critical, type/bug
