### ISSUE TITLE
RFC Archive mode should include all versioned records 

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-versioned#110] opened 2018-02-07 00:17 UTC
# Background

When viewing a historic record (or tree of records) a SilverStripe site will use the versioned `archive` mode to provide a "point in time" of the site.

The problem with this method is that it's not extremely accurate, as it doesn't take into account deleted records properly.

The "archive" logic for filtering records is the below php code:

```php
case 'archive': {
    $date = $dataQuery->getQueryParam('Versioned.date');
    if (!$date) {
        throw new InvalidArgumentException("Invalid archive date");
    }
    // Link to the version archived on that date
    $query->addWhere([
        "\"{$baseTable}_Versions\".\"Version\" IN
    (SELECT LatestVersion FROM
        (SELECT
            \"{$baseTable}_Versions\".\"RecordID\",
            MAX(\"{$baseTable}_Versions\".\"Version\") AS LatestVersion
            FROM \"{$baseTable}_Versions\"
            WHERE \"{$baseTable}_Versions\".\"LastEdited\" <= ?
            GROUP BY \"{$baseTable}_Versions\".\"RecordID\"
        ) AS \"{$baseTable}_Versions_Latest\"
        WHERE \"{$baseTable}_Versions_Latest\".\"RecordID\" = \"{$baseTable}_Versions\".\"RecordID\"
    )" => $date
    ]);
    break;
}
```

Because records that are deleted never are noted in the `_Versions` table, the `LastEdited <= ?` filter will still show the last record before it was deleted.

Note: Any feature we develop will also need to be compatible with a future recursive-rollback story https://github.com/silverstripe/silverstripe-versioned/issues/94

# Suggestions

There are a couple of ways that this problem could be solved:

## 1. Recursively write records whenever a publish occurs

When a page is saved / published, we would write everything down the stack of owned objects with a new versioned record.

When viewing a history of a particular page, instead of using `LastEdited <= ?` as a filter, we would make an exact date filter `LastEdited = ?`.

### Pros:

 - Doesn't require changes to the datamodel
 - Probably simpler to implement
 
### Cons:

 - Additional performance cost when writing records.
 - May be able to reduce cost by only doing this on publish, but sacrifices accuracy when viewing non-published record history.
 - Un-owned relations won't be accurate
 
## 2. Write deletes to _Versioned table

When a record is deleted from draft, we would create a new version in the `_Versions` table, which is a blank record, but with a new `IsDeleted` flag set to true.

The above query augmentation would be very similar, but the outer where condition would include `$query->addWhere("\"{$baseTable}_Versions\".\"IsDeleted\" = 0");`

### Pros

 - Minimial performance cost on read
 - No additional cost on write / publish
 - Not too hard to implement
 
### Cons

 - Requires additional schema for _Versioned records
 - Slightly slower file deletions
 - May confuse existing API that may not be written to understand "deleted" records existing in DB rows

## 3. Relationship versioning

Involves versioning relationships; instead of simply setting `RelationID`, we would also add `RelationVersion` to all has_one relations.

When viewing a specific parent version, the query mode would filter on this field as well as the relation, by passing the `archive` date altogether.

When viewing in mode = Draft / Live, this column would be ignored.

### Pros:

 - Provide a much more precise junction between records than date comparison
 - Queries for historic versions may be simpler (fewer subqueries = faster SQL performance)

### Cons:

 - Hardest to implement (especially in a non-breaking fashion)
 - Requires additional database columns; One column for each relation. May bloat some DB sizes with extra data.
 - Probably impossible to do without over-engineering the ORM.
 - May require the same recursive version creation as the first solution; E.g. so that that page has_many Banners will update all banner versions to point to a new page version on publish.
 - Un-owned relations won't be accurate

# Reference

Also see : 

* Parent story https://github.com/silverstripe/silverstripe-versioned/issues/93
* Story on recursive rollback https://github.com/silverstripe/silverstripe-versioned/issues/94

**Comment by chillu** [comment] 2018-02-07 20:29
Should take into account how we do rollback: https://app.zenhub.com/workspace/o/silverstripe/silverstripe-versioned/issues/94

**Comment by tractorcow** [comment] 2018-02-07 22:56
Hey I've updated the issue with a list of possible options. I'm keen to hear other ideas on other directions we could take.

My personal preference is to write deletes (Option 2).

**Comment by tractorcow** [comment] 2018-02-07 23:23
Can @silverstripe/core-team please have a look at this & leave comments / critique. :)

**Comment by sminnee** [comment] 2018-02-08 00:45
Option 2 seems reasonable.

I'd also flag that the tracking of how content is published is a bit weak - the WasPublished boolean doesn't really check _when_ the records were published, and I think there are bugs in cases where content is published and rolled back.

It may be better to have two separate support tables:

 * A list of versions
 * A list of write/publication events, to either Stage or Live. (this could be a single table with an enum for Stage/Live rather than 2 separate tables)

In this case a rollback would not create a new version but it _would_ create a new publication event.

If you were to introduce this kind of mechanism then your "delete record" would exist on the publication table rather than the versions table, I think.

**Comment by sminnee** [comment] 2018-02-08 00:58
Actually upon further thought I would recommend that ChangeSet/ChangeSetItem becomes the source of truth for these queries. It only covers published changes, not draft changes, but I don't think a history of draft changes are critical.

**Comment by tractorcow** [comment] 2018-02-08 01:02
Yep discussed this on slack... history view could easily link to changesets for "published" records (of any type) and it's a safe way to verify that something was actually published to live.

**Comment by sminnee** [comment] 2018-02-08 01:58
Yeah — declaring ChangeSet/ChangeSetItem to be the canonical record of publication events rather than a random add-on for grouped publishes will simplify a lot of things.

You don't need a separate IsDeleted flag then, either:

ChangeSetItem
 * `VersionBefore = null`: new record
 * `VersionAfter = null`: deleted record
 * Otherwise a modified record

Since we're not breaking APIs, I'd probably leave WasPublished as-is, with its current bugs/limitations, and deprecated its use.

A history viewer would quite likely list ChangeSetItems.

The "view site on this date" feature would use ChangeSetItems as its source data.

**Comment by chillu** [comment] 2018-02-08 02:16
This discussion intersects with the plans to create an "activity feed" as a way to collapse the changes across an object hierarchy (usually viewed in context of a page and all of its related objects): https://github.com/silverstripe/silverstripe-versioned/issues/68

AFAICT we can't use `ChangeSet` for this activity feed because there's no direct relationship between `ChangeSetItem`. You might publish two pages in the same set, and it's unclear to which page other items in this set belong.

> It may be better to have two separate support tables:

I'm uncomfortable with adding more support tables - versioning all the things already blows up the schema quite a bit. We've got this big transport website which will go up to 450 tables once it's all upgraded to SS4 and consistently versioned. That's ... a lot of tables. Performance of live-mode queries won't suffer more than in SS3, but dev/build and any schema-wide operations will (e.g. index creation). 

> The "view site on this date" feature would use ChangeSetItems as its source data.

We'd need to retroactively create a these items for existing versions then, right? And each `*_Versions` entry would require it's own `ChangeSet` record, because we can't tell the context of which they've been published in alongside potentially other objects.

**Comment by tractorcow** [comment] 2018-02-08 03:29
One weakness of this approach is that changests will only detect records deleted on live, `archive` mode won't be useful for browsing unpublished views.

We'll probably need both changesets + IsDeleted columns to track unpublished deletions.

**Comment by tractorcow** [comment] 2018-02-11 21:26
> It may be better to have two separate support tables:
> A list of versions
> A list of write/publication events, to either Stage or Live. (this could be a single table with an enum for Stage/Live rather than 2 separate tables).
> The publication events probably wouldn't store any actual content, just references:

I think this is probably going to be the hardest to implement, given the scope of adding yet again another set of tables. Be aware that Fluent, for example, duplicates and joins all of the tables created by versioned, so you would be increasing the number of tables by `2 x hierarchy depth x number of records` in CWP, plus `number of locales x number of tables` increase in the number of rows created overall.

**Comment by robbieaverill** [comment] 2018-02-11 22:36
I tend to agree with the idea that ChangeSets are a sensible place to centre this kind of logic. I share @chillu's concern that it might not work for data B/C if existing versioned items aren't already in ChangeSets though.

I really like the idea of option 3 (tracking a relation's version as well as its ID). Personally, I wouldn't be too concerned with the extra column nor the data in it, since it'll just be an int. Not breaking APIs would be a concern with the option, but having properly structured data relationships would be a hugely important consideration for this idea going forwards. String matching dates for determining data relationships isn't ideal.

**Comment by tractorcow** [comment] 2018-02-12 01:21
> I tend to agree with the idea that ChangeSets are a sensible place to centre this kind of logic. I share @chillu's concern that it might not work for data B/C if existing versioned items aren't already in ChangeSets though.

The problem is that there are no changesets at all for unpublished changes. Version history needs to show archive for all records not just ones that were a part of a changeset.

I think that integrating changesets with versioned history is a separate concern to this story.

**Comment by tractorcow** [comment] 2018-02-12 01:46
@chillu product owner question for you; Is it ok if we ignore liveArchive / draftArchive for the purpose of this story?

At the moment archive is "archive of all versions" without trying to filter out only those records published at the point in time. This is essentially draftArchive.

Implementing a liveArchive would be additional work, and may require many of the changeset integrations @sminnee had discussed above.

If the archive is simply a history of draft versions is it still just as useful? Is the distinction between live and draft archives too complicated?

**Comment by chillu** [comment] 2018-02-12 02:36
> Respects stage selection: Shows draft or live stage in archive date

I've removed that AC from the parent story (#93) last week This leaves a spec gap though. Consider the following from the intro of this card:

> Users can select an older version and preview a page at this past state. In SilverStripe 4, we're relying on versioned objects and nested relationships more strongly. These should be consistently included in previews of older versions.

The main point of this is for users to view all *published* records on an archived page. As an author, you'd mostly want to know a) what info your visitors saw at a certain point in time, and b) what state you're going to restore back to. 

> If the archive is simply a history of draft versions is it still just as useful? Is the distinction between live and draft archives worth the additional engineering?

Given the above, the distinction is useful and necessary.

**Comment by tractorcow** [comment] 2018-02-12 02:50
Ok, well archive of a published state would require us to use ChangeSets a lot more consistently. At the moment we use them only for publish action, but we would need to use them also for any operations that touched Live. We would need to use it for Unpublish actions as well.

Secondly we may need to use changesets for archive as well.

Yet again we have a problem of cross-stage versioned pollutions; Even if we track deletions on live, we need a way of preventing draftArchive from seeing those deletions (since they may be unpublished but not deleted from draft).

E.g. PageID 1 Version 2 was on draft last week, but it wasn't published until yesterday.

We could solve this by never sharing version IDs between stages; Each version would only ever be on one stage, and publishing between stages would create a new version.

The cost of this is that every publish would have to duplicate a Version. Thus, draftArchive would filter by WasPublished = 0, and liveArchive would filter by WasPublished = 1 (note, substitute inner join on ChangeSet also works here).

In the case of unpublish, we create a new IsDeleted = 1 WasPublished = 1 record. In the case of archive, we create TWO new records, one IsDeleted = 1, one WasPublished = 0 and the other WasPublished = 1.

If you want to add this A/C I can write up the technical considerations in full and add it to the story.

**Comment by chillu** [comment] 2018-02-12 02:50
I've also just realised that we'll need to use that "archive mode" for CMS readonly views of the edit form. The original record (e.g. the page) will already be loaded in the right version, but any related records (e.g. a readonly GridField) isn't. And that principle needs to extend to the diff view between two versions. 

For now, I've added three ACs to #93 to clarify that. We might need to split those up if it gets too much.

>  * The archive mode includes nested relationships for the website preview panel
>  * The archive mode includes nested relationships for readonly CMS form showing the record (incl. related records shown there)
>  * The archive mode includes nested relationships for diff views between two versions of a record

**Comment by tractorcow** [comment] 2018-02-12 02:52
Also, we separate archive / archiveLive versioned modes. :D

**Comment by frankmullenger** [comment] 2018-02-12 03:43
From my perspective (for satisfying the business case we have):

Option 2 seems like a good option, using date fields to determine the collection of objects at a given point in time using a range like `>= version1.timestamp AND < version2.timestamp` seems accurate enough if deleted versions are not mistakenly included.

Agree that previously published versions are most likely what content authors are interested in, presenting draft versions seems over complicated from a content author perspective and of limited use (not that I've validated this hunch).

>  WasPublished boolean doesn't really check when the records were published, and I think there are bugs in cases where content is published, rolled back, and republished

It would be nice to have an accurate timestamp for when a page was published, however as long as the data retrieved for the version is accurate it's probably less important (for us at least). 

Aside: personally I'd be happy if _versions records are immutable e.g: they are not updated when a record is moved from one stage to another but rather a new record is created. In this case the _versioned table becomes the canonical record in some sense and WasPublished rows would have an accurate timestamp. Likewise for archived records when a _version is deleted, a new row is created rather than an existing row updated.

**Comment by tractorcow** [comment] 2018-02-12 03:44
Also there was discussion about whether or not we need to track _Versioned archive for non-published changes.

Should _Versioned be ONLY published records? That would completely disable the "show unpublished records" in history viewer.

**Comment by tractorcow** [comment] 2018-02-12 05:33
I had a chat with Benn Crawford and said that eventually we'll need to support non-live archive as well, so live-only history isn't going to be feasible.

**Comment by tractorcow** [comment] 2018-02-12 23:20
@chillu to clarify:

What I'm proposing is that we support both modes:

 `/mypage/?archiveDate=2010-03-04&stage=Stage` <- Provides a historic view of the version history draft mode (WasPublished = 0)
  `/mypage/?archiveDate=2010-03-04&stage=Live` <- Provides a historic view of the version history live mode (WasPublished = 1)
  
At the moment archiveDate does absolutely no stage filtering, and instead shows both staged merged together, producing a completely erroneous historic view of the history.

My proposal requires the following:

 - Implementation of option 2. in the initial story (record all deletes via IsDeleted = 1 columns)
 - Add another `WasDraft` flag to versioned to complement `WasPublished`
 - Unpublish actions create `WasPublished = 1, WasDraft = 0, IsDeleted = 1`
 - Archive actions create `WasPublished = 1, WasDraft = 1, IsDeleted = 1`
 - Delete (draft only) creates `WasPublished = 0, WasDraft = 1, IsDeleted = 1`
 - Ensure that archiveMode provides an additional filter based on stage. stage=Live filters only by records with WasPublished=1. stage=Draft filters only by WasDraft=1

**Comment by chillu** [comment] 2018-02-13 21:45
Good call. I thought about restricting `_Versioned` records to published ones a bit more, and agree that we need unpublished. Not sure if it's for the same reason as Benn, but my take is that there's two important use cases relying on it:

 * Compare the *latest* draft with the *latest* published version, effectively previewing what you're about to publish
 * Attribute edits to their original author (which might be different from the one who published the work)

Shouldn't `IsDeleted` be `WasDeleted` for consistency? You can un-delete records, right?

> Ensure that archiveMode provides an additional filter based on stage. stage=Live filters only by records with WasPublished=1. stage=Draft filters only by WasDraft=1

That seems error prone - I think `stage=Draft` shouldn't filter at all. If your objective is to view a page (either in draft or live) at a certain point in time, filtering by `WasDraft=1` will mean you might show *earlier* drafts, even when a later published state exists that users (and authors) would've actually seen on the website or preview at that point in time.

> A variant to the above is to not have the WasDraft column, and always create a new row for published / draft versions. However, this breaks the isModifiedOnDraft since draft version never === live version number. Something else may need to be solved for this (maybe modified requires Version number to differ by at least 2?)

I don't think the complexity is warranted if the goal is to save us from creating a new column. This column will make other querying use cases easier as well.

Would we need any data migration for historic versions? I guess anything before the new data model would just be less accurate, but not any worse than it is today?

**Comment by tractorcow** [comment] 2018-02-13 22:30
Short answer to the above (and we'd discussed this on slack): Unpublish changes need to be live-only, so ignoring filter for Stage=Draft won't work.
 
Instead of creating a new column, we could replace `WasPublished` with a `Stage` enum, which is `Live`, `Draft` or `Both` (or some variant) and filter on that instead.

All publish actions MUST create a new version, rather than retroactively modify historic versions.

E.g.
```
version 5, Stage=Draft
->publishSingle()
veresion 6, Stage=Both
->unpublish
version 7: Stage=Live, IsDeleted=1
```

This may require us to stop respecting the $createNewVersion of copyVersionToStage() method. writes to versioned will now be a lot more aggressive with new version creation.

**Comment by chillu** [comment] 2018-02-14 03:46
> All publish actions MUST create a new version, rather than retroactively modify historic versions.

I think that's the cleanest, even if it creates more records. I'm assuming we'd need a migration script to switch over the existing values for the `WasPublished` column, and that's something we're happy to do in a 4.2 release?

> This may require us to stop respecting the $createNewVersion of copyVersionToStage() method. writes to versioned will now be a lot more aggressive with new version creation.

That seems like an unavoidable change to a minor API. Particularly since it's `false` by default, and if you're using this API you're opting in to creating versions - which is now the default behaviour anyway.

**Comment by tractorcow** [comment] 2018-02-14 20:52
> I think that's the cleanest, even if it creates more records. I'm assuming we'd need a migration script to switch over the existing values for the WasPublished column, and that's something we're happy to do in a 4.2 release?

Yeah that probably won't be too hard. We can make it an upgrading note in 4.2.0.md.

**Comment by tractorcow** [comment] 2018-02-15 00:44
# Overview

Content authors, owners and auditors want to have certainty that changes to the website are recorded correctly, both for auditing purposes and to restore content to an earlier state. The main way this detail is exposed to users is through the "History" view. Users can select an older version and preview a page at this past state. In SilverStripe 4, we're relying on versioned objects and nested relationships more strongly. These should be consistently included in previews of older versions.

In order to support this the version history behaviour will be enhanced and extended to provide a more "exact" historical audit of all actions taken on an object.

# Acceptance Criteria

 * The archive mode includes nested relationships for the website preview panel
 * The archive mode includes nested relationships for readonly CMS form showing the record (incl. related records shown there)
 * Works with nested versioned relationships (e.g. Page has_many GalleryContentBlock has_many GalleryItem has_one Image)
 * Works regardless of ownership on relationship
 * Works with has_one
 * Works with has_many
 * Works with [many_many through](https://docs.silverstripe.org/en/4/developer_guides/model/relations/#many-many-through-relationship-joined-on-a-separate-dataobject) where all three models are versioned
 * Respects sort order on has_many and many_many
 * Hides records which have been created after the previewed version
 * Hides records which have been created before the previewed version, but have been associated through a versioned relationship after the previewed version
 * Shows records which have been deleted after the previewed version
 * Does not rely on specific version associations in versioned relationships (uses archive date)
 
(new A/C)
 
 * works with belongs_to
 * Respects the given stage of the versioned record. I.e. viewing an unpublished record will show the stage version of all nested records, but viewing the published record will show the live website at that point in time.
 * Respects records which have been unpublished (but not deleted), either by showing them on draft, or not showing them on live.

(removed A/C)

 * The archive mode includes nested relationships for diff views between two versions of a record

# Technical implementation details

* Deleted records will now create a `_Versioned` row with `WasDeleted` flag set to true.
* `_Versioned` rows will now record a flag for all stages this row affects. This could either by adding a `Stages` enum (Draft/Live/Both), or by adding a `WasDraft` to complement `WasPublished`.
* Any changes that modify live will now create a new version, even if copying from the draft. This is because historic _Versioned rows cannot "change" the stage they originally aplied to. This may require us to ignore the `$createNewVersion` flag on copyVersionToStage, and force it to true.
* Ensure that unpublish actions creates a WasDeleted = true, stage=Live row
* Ensure that archive actions creates a WasDeleted = true, stage=Both row
* Ensure that delete (draft only) creates a WasDeleted = true, stage=Draft row

**Comment by chillu** [comment] 2018-02-15 01:01
Just thinking through how that'd look like on the "Delete owned with republishing owner" scenario.

Create Page1:
`ClassName: Page, ID: 1, Version: 1, LastEdited: 10:00, WasDeleted: 0, WasPublished: 0, Stage: Draft`

Publish Page1v1:
`ClassName: Page, ID: 1, Version: 2, LastEdited: 10:01, WasDeleted: 0, WasPublished: 1, Stage: Both`

Create GalleryBlock1, add to Page1
`ClassName: GalleryBlock ID: 1, Version: 1, PageID: 1, LastEdited: 10:02, WasDeleted: 0, WasPublished: 0, Stage: Draft`

Publish Page1v3 (publishes GalleryBlock1v2):
`ClassName: Page ID: 1, Version: 3, LastEdited: 10:03, WasDeleted: 0, WasPublished: 1, Stage: Both`
`ClassName: GalleryBlock ID: 1, Version: 2, PageID: 1, LastEdited: 10:03, WasDeleted: 0, WasPublished: 1, Stage: Both`

Delete GalleryBlock1 ("archive"):
`ClassName: GalleryBlock ID: 1, Version: 3, PageID: 1, LastEdited: 10:05, WasDeleted: 1, WasPublished: 0, Stage: Both`

Publish Page1v4
`ClassName: Page ID: 1, Version: 4, LastEdited: 10:06, WasDeleted: 0, WasPublished: 1, Stage: Both`

Expected: Viewing Page1v4 in "Live" archive mode should not show GalleryBlock1.

Queries (rough):
`SELECT * FROM SiteTree_Versions WHERE ID=1 AND LastEdited <= 10:06 AND WasPublished=1`
`SELECT * FROM GalleryBlock_Versions WHERE ID=1 AND LastEdited <= 10:06 AND LastEdited >= <SiteTree.LastEdited> WasPublished=1`

So the second query relies on the date of the version retrieved in the first query. Would that work?

**Comment by tractorcow** [comment] 2018-02-15 01:05
Yes that's how archive works in principle. The only changes are that now we need a special filter on the subquery join for deleted records (we still join them, but second outer query filters them out), and the addition of the `Stage=whatever` condition. ;P

**Comment by tractorcow** [comment] 2018-02-15 01:09
```
SELECT * FROM "SiteTree_Versions" WHERE "RecordID" = ? AND "VersionID" = 
(
	SELECT MAX "VersionID" FROM "SiteTree_Versioned"
	WHERE "LastEdited" < ?
        AND "Stage" in ("Both", ?)
	AND "RecordID" = ?
)
WHERE "IsDeleted" = 0
```

**Comment by tractorcow** [comment] 2018-02-15 01:09
Notice the inner query captures the deleted rows, to ensure the outer query can filter it out ;P

**Comment by chillu** [comment] 2018-02-15 19:46
Sweet, enough RFC'ing, I've updated the parent card with the outcome

**Closed** 2018-02-15 19:45 UTC
Labels: affects/v4, change/minor, effort/medium, impact/high, rfc/draft, type/enhancement
