### ISSUE TITLE
Archive popup contains no content

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-versioned#206] opened 2019-01-16 23:06 UTC
When selecting to archive an item from a gridfield, an empty popup is shown without any information

**Comment by robbieaverill** [comment] 2019-01-17 08:49
Closing as a duplicate of https://github.com/silverstripe/silverstripe-admin/issues/753

This has been fixed in SS 4.3 and will be in the next release =)

**Closed by robbieaverill** 2019-01-17 08:49 UTC
