### ISSUE TITLE
Is Archive the same as Delete or where is the real Delete?

### ISSUE THREAD

**Issue by colymba** [silverstripe/silverstripe-versioned#40] opened 2017-08-29 07:29 UTC
This is more of a question/discussion at this point, when handling Versioned DataObject, the CMS buttons change to the ones below, which is great but leaves some confusion:
![screen shot 2017-08-29 at 10 17 51](https://user-images.githubusercontent.com/978040/29809179-d87b8e18-8ca3-11e7-9b3a-3faf80a63379.png)

Actually deleting a record seems to not be available, while Archive essentially has the same effect at this point (only leaving entries in the Versions table).

I think some of this confusion is mentioned here https://github.com/silverstripe/silverstripe-versioned/issues/38.

The Archiving behaviour should be solved and make more sense once we have an actual Version browsing mechanism in place. But would it still make sense to have an actual Delete button, which would purge all records entries in all tables including the Versions table?

**Comment by dhensby** [comment] 2017-08-29 12:07
related:

- https://github.com/silverstripe/silverstripe-framework/issues/6202
- https://github.com/silverstripe/silverstripe-cms/issues/1575
- https://github.com/silverstripe/silverstripe-cms/issues/1227
- https://github.com/silverstripe/silverstripe-framework/pull/4189
- https://github.com/silverstripe/silverstripe-cms/pull/1203
- https://github.com/silverstripe/silverstripe-framework/issues/6059

This has been raised repeatedly and covered fairly well. At the moment there's no real desire for the ability to irrevocably delete versioned objects, though it has been raised before. Contributions that add this feature would probably be considered but may well be worth starting out as its own module.

Closing as duplicate/question/not a bug

**Closed by dhensby** 2017-08-29 12:07 UTC
